# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='url',
            field=models.ManyToManyField(blank=True, null=True, to='searcher.Page'),
        ),
    ]
