# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='url',
            field=models.ManyToManyField(blank=True, to='searcher.Page'),
        ),
    ]
