# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_auto_20160616_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
